# Generated by Django 2.2.1 on 2019-05-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, upload_to='user_images/profile/%Y/%m/%d'),
        ),
    ]
